export function detectLanguage(fileName: string) {
    //@ts-ignore
    const extension = fileName.split('.').pop().toLowerCase();

    switch (extension) {
        case 'js':
            return 'javascript';
        case 'py':
            return 'python';
        case 'java':
            return 'java';
        case 'html':
            return 'html';
        case 'css':
            return 'css';
        case 'php':
            return 'php';
        case 'rb':
            return 'ruby';
        case 'cpp':
            return 'c++';
        case 'c':
            return 'c';
        case 'swift':
            return 'swift';
        case 'kt':
            return 'kotlin';
        case 'ts':
            return 'typescript';
        case 'scala':
            return 'scala';
        case 'go':
            return 'go';
        case 'rs':
            return 'rust';
        case 'lua':
            return 'lua';
        case 'sh':
            return 'bash';
        case 'pl':
            return 'perl';
        case 'coffee':
            return 'coffeescript';
        case 'dart':
            return 'dart';
        case 'jsx':
            return 'javascript';
        case 'tsx':
            return 'typescript';
        case 'r':
            return 'r';
        case 'sql':
            return 'sql';
        case 'scss':
            return 'css';
        case 'sass':
            return 'css';
        case 'less':
            return 'less';
        case 'json':
            return 'json';
        case 'xml':
            return 'xml';
        case 'yml':
            return 'yaml';
        case 'ini':
            return 'ini';
        case 'toml':
            return 'toml';
        case 'csv':
            return 'csv';
        case 'tsv':
            return 'tsv';
        case 'md':
            return 'markdown';
        case 'txt':
            return 'plaintext';
        case 'svg':
            return 'svg';
        case 'vue':
            return 'vue';
        case 'ejs':
            return 'ejs';
        case 'pug':
            return 'pug';
        case 'hbs':
            return 'handlebars';
        case 'styl':
            return 'stylus';
        case 'graphql':
            return 'graphql';
        case 'lisp':
            return 'lisp';
        case 'clj':
            return 'clojure';
        case 'asm':
            return 'assembly';
        case 'awk':
            return 'awk';
        case 'bat':
            return 'batchfile';
        case 'cs':
            return 'csharp'; // C# added here
        case 'cbl':
            return 'cobol';
        case 'd':
            return 'd';
        case 'ex':
            return 'elixir';
        case 'erl':
            return 'erlang';
        case 'fs':
            return 'fsharp';
        case 'f90':
            return 'fortran';
        case 'hs':
            return 'haskell';
        case 'plsql':
            return 'plsql';
        case 'proto':
            return 'protobuf';
        case 'tcl':
            return 'tcl';
        case 'vb':
            return 'vb';
        case 'yaml':
            return 'yaml';
        default:
            return 'text'; // Or handle other cases appropriately
    }
}